name: nassan_app
description: "Alnassan App Islamic App"
publish_to: 'none' # لا تنشر على pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_gen: ^5.11.0
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  collection: ^1.17.2
  country_picker: 2.0.27
  dotted_border: ^3.1.0
  dropdown_search: 6.0.2
  flutter_image_compress: ^2.0.4
  flutter_screenutil: ^5.9.3
  flutter_slidable: ^4.0.1
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.2
  flutter_staggered_grid_view: 0.7.0
  flutter_svg: ^2.2.0
  freezed: ^3.0.0-0.0.dev
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  go_router: ^16.2.0
  google_fonts: ^6.3.1
  google_maps_flutter: ^2.12.3
  image_picker: ^1.2.0
  infinite_scroll_pagination: ^5.1.1
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: 4.9.0
  json_serializable: ^6.11.0
  loading_animation_widget: 1.3.0
  logger: ^2.6.1
  lottie: 3.3.1
  path: 1.9.1
  path_provider: 2.1.5
  pdf: 3.11.3
  skeletonizer: ^2.1.0+1
  text_scroll: 0.2.0
  uuid: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.0
  flutter_gen_runner: ^5.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Tajwal
      fonts:
        - asset: assets/fonts/Tajwal-Regular.ttf
        - asset: assets/fonts/Tajwal-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    image: true
    flutter_svg: true
